flags: {}
packages:
- lambdacmsorg-base
- lambdacmsorg-page
- lambdacmsorg-tutorial
extra-deps:
- lambdacms-core-0.3.0.2
- friendly-time-0.4
- lists-0.4.2
- list-extras-0.4.1.4
resolver: nightly-2015-07-24
